# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 552ba6e24bb1b5688fe1618d9f8559601fb361b0110619b6d762d53ba047fe8a234bb511478b6d1842bbb1379c33b75bf02f32337a31e8d1061184aee8574c81

test:
  secret_key_base: 4b3d4742dc0e50b51aabdc6fee1cfcc421de454c91ebd8d88114f0bbaecc830de10eafa603aceb5e250b03671cfb767d70866b59815e2887ab3f3add7cc75e34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
